### PR TITLE
Small changes to ch12 and ch13

### PR DESCRIPTION
**Pull request by Nowosad**
One additional comment: there is a spurious (?) message in both chapters related to plotting the data - `"# Coordinate system already present. Adding new coordinate system, which will replace the existing one."`.

### CODE REVIEW

**Comment by Nowosad** [comment]
@edzer now, I have added also small changes to ch14 and ch15. Some additional comments for these chapters:

Chapter 14:

- \@ref(spatecon_pred) does not exist
- There is something wrong with the @R-igraph citation  (`file., See AUTHORS. 2020. Igraph: Network Analysis and Visualization. https://igraph.org.`)

Chapter 15:

- "One characteristic of distance-based neighbours is that more densely settled areas, with units which are smaller in terms of area" - I do not understand this sentence...
- "In the local case, conditional permutation may be used, fixing the value at observation $i$ and randomly sampling from the remaining $n-1$ values to find randomised values at neighbours, and is provided as `localmoran_perm()`, which may use multiple nodes to sample in parallel if provided, and permits the setting of a seed for the random number generator across the compute nodes:" - This sentence is very long and complex. Maybe it would be better for readers to split it into 2-3 shorter sentences?
- Figure 15.5 is not visible online- https://keen-swartz-3146c4.netlify.app/spatautocorr.html#fig:localmoranZsad

**Comment by Nowosad** [comment]
@edzer There are also changes to ch16 and ch17.

Chapter 17 - additional comment:

- "Another useful finding is that the presence of residual spatial autocorrelation need not bias the estimates of variance of regression coefficients, provided that the covariates themselves do not exhibit spatial autocorrelation" - I do not understand this sentence

**Comment by edzer** [comment]
Great, thanks @Nowosad !

**Comment by Nowosad** [comment]
Happy to be helpful. 
Thank you for the book - I have learned a lot while reading it, and many of its parts will be helpful as pointers to my students.

**Comment by edzer** [comment]
I will suggest C&H to approach you for a review - you've done the heavy part now!

**Pull request merged**
