### PR TITLE
Tmap4

### PR DESCRIPTION
**Pull request by rsbivand**
More or less OK for `tmap` 4 (current repo HEAD); still need to check some `set.seed` etc., as some figures diverge marginally, affecting the category count in the legend, displacing objects in the figure(s). #119

### CODE REVIEW

**Comment by rsbivand** [comment]
... still have two figures in ch 16 to go.

**Comment by rsbivand** [comment]
I didn't try to hide the conditioning code, but I guess that would be needed where it is exposed (I haven't seen any yet, but didn't look carefully).

**Comment by rsbivand** [comment]
Should be OK now for ch 14-16.

**Comment by edzer** [comment]
Shall I merge so we can see the results?

**Comment by rsbivand** [comment]
I think so, please try!

**Comment by edzer** [comment]
Changes in rendered pages: https://github.com/edzer/sdsr/commit/787cd09bd62e845fd51d93f94d9604c75d535bfa

**Comment by rsbivand** [comment]
It doesn't seem easy to get everything to match identically, but I think it is pretty close. In chs 14-16, the changes are as intended. I'm still not completely sure about getting `tm_facets` to behave as I intend, it seems to override my choice of column and row numbers, but I can accept the new behaviour.

**Comment by Nowosad** [comment]
@rsbivand I think your problem with `tm_facets()` is related to https://github.com/r-tmap/tmap/issues/713

**Comment by rsbivand** [comment]
@Nowosad I've tried `tm_facets_wrap`, which does take `columns=` and `rows=` as arguments, but doesn't seem to follow them. It would also be useful to place the legend in one of the cells too, but that can wait. An example: https://github.com/edzer/sdsr/blob/67368eaace9633f4809ce7e626051a00e4f663ec/scripts/15-Measures.R#L307-L318 asks for 2 columns and gets three: 
image

**Pull request merged**
