### PR TITLE
Split 17

### PR DESCRIPTION
**Pull request by rsbivand**
This is an attempt to split 17 into two parts. 18 will follow.

I think #crs may need to mention datum ensembles.

### CODE REVIEW

**Comment by edzer** [comment]
This PR removes pretty much the entire rendered book (in `_book`) - intentionally?

**Comment by rsbivand** [comment]
No idea - I ran 

```
make clean
make book
```
Should I rather just `make book` ?

**Comment by edzer** [comment]
`git add _book` ?

**Comment by rsbivand** [comment]
No `_book` on my system. Fetching upstream nothing. PRs cumulate it seems by default, instead of working intuitively. Not only are tidyverse/ggplot not my friends, github is loosing out in a major way. 

I thought that it didn't matter that _book etc. are local and not on git, but probably because your _book has to be on github to run netlify, it gets inserted into my repo too, even though I never added _book.

**Comment by edzer** [comment]
You committed the removal of `_book`, that's all. Let me know when this is ready to merge, I'll fix it in master.

**Comment by rsbivand** [comment]
No, I just cleaned up my repo with `make clean`. _book should be somewhere else? Trying to merge upstream, I now have conflicts in all the _book/*. How can I automatically fix the conflicts (like SVN prefer theirs)?

**Comment by edzer** [comment]
> How can I automatically fix the conflicts (like SVN prefer theirs)? git checkout --theirs _book

I don't know.

**Comment by rsbivand** [comment]
`git checkout --theirs _book` did "work" in a git-like way. _book rebuilt. Should I add:

```
	_book/reference-keys.txt
	_book/spatautocorr.html
	_book/spatglmm.html
	_book/style.css
```
to my repo?

**Comment by edzer** [comment]
Oh, good! Yes, please add the files that need to be added.

**Comment by edzer** [comment]
As usual, you can verify the rendering of the PR at https://deploy-preview-46--keen-swartz-3146c4.netlify.app/ (replace 46 with the PR number).

**Comment by rsbivand** [comment]
Another question: can I expose all the code in what I'm writing? The HTML click for code block are really destructive of reading text and code together. Can this be defined per chapter/Rmd file?

**Comment by rsbivand** [comment]
It would also be excellent if tidyverse was absent unless required - I get lots of `The following objects are masked from 'package:tidyr'` and similar; can tidy simply be restricted to chapters using it? It isn't core functionality for any kind of data science, it is syntactic sugar only. I'm going to have to edit in `warn.conflicts=FALSE` in all informative `library()` usage. 

This is only needed because **bookdown** first catenates the *.Rmd files, so anything loaded/attached earlier provokes subsequent conflicts. If bookdown could build *.html or *.tex by Rmd file, it would work better. 

This was the same problem I had building the whole R Journal issue from many *.tex files, with label and bibtex key conflicts. It became easier to build article PDFs with correct pagination and glue them together afterwards.

**Comment by edzer** [comment]
I haven't found a way to do this per chapter/Rmd file. You can do it per chunk by setting `echo=FALSE`. The plan is for the pdf to have Ch 1-6 all chunks echo switched off, all other chapters switched on; this already works. I still need to hack this code hide/show thing to also make this default on the html version (or, indeed, set it on a per-chapter basis).

As of the tidyverse masking: I'll look into whether detaching it helps.

**Comment by edzer** [comment]
The PR doesn't render yet; did you add & commit `_book/reference-keys.txt` and `_book/style.css`?

**Comment by rsbivand** [comment]
Now:
```
$ git status
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	_book/images/
	_book/libs/
	_book/sds_files/figure-html/Iihotspots-1.png
	_book/sds_files/figure-html/airagg-1.png
	_book/sds_files/figure-html/airmap-1.png
	_book/sds_files/figure-html/airst-1.png
	_book/sds_files/figure-html/airts-1.png
	_book/sds_files/figure-html/antarctica-1.png
	_book/sds_files/figure-html/aqdc-1.png
	_book/sds_files/figure-html/asstars-1.png
	_book/sds_files/figure-html/awiex-1.png
	_book/sds_files/figure-html/boxes-1.png
	_book/sds_files/figure-html/bristol1-1.png
	_book/sds_files/figure-html/circr-1.png
	_book/sds_files/figure-html/computestationmeans-1.png
	_book/sds_files/figure-html/computevariogram-1.png
	_book/sds_files/figure-html/controlcutoff-1.png
	_book/sds_files/figure-html/cube-1.png
	_book/sds_files/figure-html/cube4agg-1.png
	_book/sds_files/figure-html/cube4apply1-1.png
	_book/sds_files/figure-html/cube4apply2-1.png
	_book/sds_files/figure-html/cube4d-1.png
	_book/sds_files/figure-html/cube4d2-1.png
	_book/sds_files/figure-html/cube4filter-1.png
	_book/sds_files/figure-html/cube4reduce-1.png
	_book/sds_files/figure-html/de9im-1.png
	_book/sds_files/figure-html/diff-1.png
	_book/sds_files/figure-html/ellipse-1.png
	_book/sds_files/figure-html/eqc-1.png
	_book/sds_files/figure-html/fig57-1.png
	_book/sds_files/figure-html/figreset-1.png
	_book/sds_files/figure-html/first-map-1.png
	_book/sds_files/figure-html/firstgather-1.png
	_book/sds_files/figure-html/firststars-1.png
	_book/sds_files/figure-html/fitprodsummodel-1.png
	_book/sds_files/figure-html/fitvariogrammodel-1.png
	_book/sds_files/figure-html/ggplotstars-1.png
	_book/sds_files/figure-html/horizontalgrid-1.png
	_book/sds_files/figure-html/idw-1.png
	_book/sds_files/figure-html/largest-1.png
	_book/sds_files/figure-html/lda-1.png
	_book/sds_files/figure-html/lineras-1.png
	_book/sds_files/figure-html/localG-1.png
	_book/sds_files/figure-html/localZvalues-1.png
	_book/sds_files/figure-html/localmoranZ-1.png
	_book/sds_files/figure-html/moranhat-1.png
	_book/sds_files/figure-html/moranplot-1.png
	_book/sds_files/figure-html/multi-levelcoefs-1.png
	_book/sds_files/figure-html/multi-levelmaps1-1.png
	_book/sds_files/figure-html/multilevelmaps2-1.png
	_book/sds_files/figure-html/ncaggregation-1.png
	_book/sds_files/figure-html/ncblocks-1.png
	_book/sds_files/figure-html/no2scat-1.png
	_book/sds_files/figure-html/odbykm-1.png
	_book/sds_files/figure-html/odjoined-1.png
	_book/sds_files/figure-html/odm33-1.png
	_book/sds_files/figure-html/orangebuffer-1.png
	_book/sds_files/figure-html/overpass-1.png
	_book/sds_files/figure-html/plotkrigingvalues-1.png
	_book/sds_files/figure-html/plotnbdiff-1.png
	_book/sds_files/figure-html/plotp-1.png
	_book/sds_files/figure-html/plotpolpres15-1.png
	_book/sds_files/figure-html/plotprodsummodel-1.png
	_book/sds_files/figure-html/plotvariograms-1.png
	_book/sds_files/figure-html/polar-1.png
	_book/sds_files/figure-html/predictusingpopulationdensity-1.png
	_book/sds_files/figure-html/ras-1.png
	_book/sds_files/figure-html/rasterizeline-1.png
	_book/sds_files/figure-html/rastertypes01-1.png
	_book/sds_files/figure-html/rsample-1.png
	_book/sds_files/figure-html/sfgeometries-1.png
	_book/sds_files/figure-html/shortestpath-1.png
	_book/sds_files/figure-html/spacetimekriging-1.png
	_book/sds_files/figure-html/sphere-1.png
	_book/sds_files/figure-html/starshook-1.png
	_book/sds_files/figure-html/starsrgb-1.png
	_book/sds_files/figure-html/tmapnc-1.png
	_book/sds_files/figure-html/tmapnc2-1.png
	_book/sds_files/figure-html/tmapstars-1.png
	_book/sds_files/figure-html/unnamed-chunk-127-1.png
	_book/sds_files/figure-html/unnamed-chunk-130-1.png
	_book/sds_files/figure-html/unnamed-chunk-132-1.png
	_book/sds_files/figure-html/unnamed-chunk-134-1.png
	_book/sds_files/figure-html/unnamed-chunk-136-1.png
	_book/sds_files/figure-html/vectoras-1.png
	_book/sds_files/figure-html/verticalgrid-1.png
	_book/sds_files/figure-html/vor-1.png
	_book/sds_files/figure-html/world-1.png
... all the aq files
	aq/pop/
	data/ms.osm
	data/uk_os_OSGM15_GB.tif
	data/uk_os_OSTN15_NTv2_OSGBtoETRS.tif
	sds.aux
	sds.blg
	sds.log
	sds.toc
```
so I think they were added, committed and pushed.

**Comment by rsbivand** [comment]
I've I hope done most of the work on 14-17, committed and pushed. Do you need to know which packages/versions I used?

**Comment by edzer** [comment]
Great, merged now and uploaded.

**Pull request merged**
