### PR TITLE
Small changes to ch1 and ch2

### PR DESCRIPTION
**Pull request by Nowosad**
Dear @edzer,
I just started reading **sdsr** and have been making small changes to the source text. In this PR, you can find modifications for the first two chapters - they are mostly related to improve text consistency and fix typos. 
I also find two additional issues: (1) Section `\@ref(axisorder)` does not exist, but it is called two times in your book, and (2) some code chunks (for example, in chapter 2) have `echo=!knitr::is_latex_output()`, however, I would assume you want to have them in the paper version of the book.
Additionally, I have one question - what are the "insides and outsides of polygons" (https://keen-swartz-3146c4.netlify.app/cs.html#bounded)? I was unable to understand this from the text.

Let me know if this is useful for you. If so, I will try to create similar PRs for the next chapters as well.
Best,
Jakub

### CODE REVIEW

**Comment by edzer** [comment]
Thanks, Jakub, useful! Chapters 1-6 of the print edition are meant to not show code sections, only output.

**Comment by Nowosad** [comment]
I know this, but there (maybe) should be some exceptions from this rule. For example, take a look at the second code chunk at https://keen-swartz-3146c4.netlify.app/cs.html#ellipsoidal-coordinates-1.

**Comment by edzer** [comment]
Ah, you mean there `echo` should be `FALSE`, as of, always?

**Comment by Nowosad** [comment]
I was wrong about this issue. It is fine.

**Pull request merged**
